//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicNtierTemplate.Web.MVC.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegisterViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterViewModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BasicNtierTemplate.Web.MVC.Resources.RegisterViewModel", typeof(RegisterViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string EDIT_USER_CITY_LABEL {
            get {
                return ResourceManager.GetString("EDIT_USER_CITY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        public static string EDIT_USER_EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EDIT_USER_EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid email address.
        /// </summary>
        public static string EDIT_USER_EMAIL_VALIDATION {
            get {
                return ResourceManager.GetString("EDIT_USER_EMAIL_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot exceed 50 characters.
        /// </summary>
        public static string EDIT_USER_FIRSTNAME_MAXLENGTH_VALIDATION {
            get {
                return ResourceManager.GetString("EDIT_USER_FIRSTNAME_MAXLENGTH_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required.
        /// </summary>
        public static string EDIT_USER_FIRSTNAME_REQUIRED {
            get {
                return ResourceManager.GetString("EDIT_USER_FIRSTNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name cannot exceed 50 characters.
        /// </summary>
        public static string EDIT_USER_LASTNAME_MAXLENGTH_VALIDATION {
            get {
                return ResourceManager.GetString("EDIT_USER_LASTNAME_MAXLENGTH_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required.
        /// </summary>
        public static string EDIT_USER_LASTNAME_REQUIRED {
            get {
                return ResourceManager.GetString("EDIT_USER_LASTNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirmation password do not match.
        /// </summary>
        public static string EDIT_USER_PASSWORD_CONFIRM_COMPARE_VALIDATION {
            get {
                return ResourceManager.GetString("EDIT_USER_PASSWORD_CONFIRM_COMPARE_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string EDIT_USER_PASSWORD_CONFIRM_LABEL {
            get {
                return ResourceManager.GetString("EDIT_USER_PASSWORD_CONFIRM_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters.
        /// </summary>
        public static string EDIT_USER_PASSWORD_MINLENGTH_VALIDATION {
            get {
                return ResourceManager.GetString("EDIT_USER_PASSWORD_MINLENGTH_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string EDIT_USER_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("EDIT_USER_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid phone number.
        /// </summary>
        public static string EDIT_USER_PHONENUMBER_VALID {
            get {
                return ResourceManager.GetString("EDIT_USER_PHONENUMBER_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot exceed 30 characters.
        /// </summary>
        public static string EDIT_USER_USERNAME_MAXLENGTH_VALIDATION {
            get {
                return ResourceManager.GetString("EDIT_USER_USERNAME_MAXLENGTH_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username must be at least 3 characters.
        /// </summary>
        public static string EDIT_USER_USERNAME_MINLENGTH_VALIDATION {
            get {
                return ResourceManager.GetString("EDIT_USER_USERNAME_MINLENGTH_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required.
        /// </summary>
        public static string EDIT_USER_USERNAME_REQUIRED {
            get {
                return ResourceManager.GetString("EDIT_USER_USERNAME_REQUIRED", resourceCulture);
            }
        }
    }
}
