<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b933c5cd-3c03-41e4-8938-3b4d45205c6a</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
    <DockerComposeProjectPath>..\..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference
      Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets"
      Version="1.23.0"
    />
    <PackageReference Include="Microsoft.Web.LibraryManager.Build" Version="3.0.71" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ComplexNLayerTemplate.Data\ComplexNLayerTemplate.Data.csproj" />
    <ProjectReference Include="..\ComplexNLayerTemplate.Service\ComplexNLayerTemplate.Service.csproj" />
  </ItemGroup>
</Project>
