// <auto-generated />
using BasicNtierTemplate.Data.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasicNtierTemplate.Data.Migrations
{
    [DbContext(typeof(BasicNtierTemplateDbContext))]
    [Migration("20251030162727_InitialMigrationWithoutIdentity")]
    partial class InitialMigrationWithoutIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasicNtierTemplate.Data.Model.Blog", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Blog");

                    b.HasData(
                        new
                        {
                            id = 1,
                            url = "https://example.com/blog1"
                        },
                        new
                        {
                            id = 2,
                            url = "https://example.com/blog2"
                        },
                        new
                        {
                            id = 3,
                            url = "https://example.com/blog3"
                        },
                        new
                        {
                            id = 4,
                            url = "https://example.com/blog4"
                        });
                });

            modelBuilder.Entity("BasicNtierTemplate.Data.Model.Posteo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("blogid")
                        .HasColumnType("int");

                    b.Property<string>("contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("blogid");

                    b.ToTable("Posteo");

                    b.HasData(
                        new
                        {
                            id = 1,
                            blogid = 1,
                            contenido = "Content for Post 1",
                            titulo = "Post 1"
                        },
                        new
                        {
                            id = 2,
                            blogid = 1,
                            contenido = "Content for Post 2",
                            titulo = "Post 2"
                        },
                        new
                        {
                            id = 3,
                            blogid = 2,
                            contenido = "Content for Post A",
                            titulo = "Post A"
                        },
                        new
                        {
                            id = 4,
                            blogid = 3,
                            contenido = "Content for Post B",
                            titulo = "Post B"
                        },
                        new
                        {
                            id = 5,
                            blogid = 4,
                            contenido = "Content for Post C",
                            titulo = "Post C"
                        },
                        new
                        {
                            id = 6,
                            blogid = 4,
                            contenido = "Content for Post D",
                            titulo = "Post D"
                        });
                });

            modelBuilder.Entity("BasicNtierTemplate.Data.Model.Posteo", b =>
                {
                    b.HasOne("BasicNtierTemplate.Data.Model.Blog", "blog")
                        .WithMany("Posteos")
                        .HasForeignKey("blogid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("blog");
                });

            modelBuilder.Entity("BasicNtierTemplate.Data.Model.Blog", b =>
                {
                    b.Navigation("Posteos");
                });
#pragma warning restore 612, 618
        }
    }
}
