@CleanArchitectureTemplate.Server_HostAddress = http://localhost:5018

# NOTE: Work correctly withOUT JWT

### Register
POST {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/register
Accept: application/json
Content-Type: application/json

{
  "email": "user2@test.com",
  "password": "P@ssw0rd!",
  "confirmPassword": "P@ssw0rd!"
}

### WITH OPAQUE BEARER TOKENS #############################################

### Login - Without query parameters
# Returns: Bearer tokens
POST {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/login
Accept: application/json
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "P@ssw0rd!"
}

### LogOut
# Requires: Bearer tokens
@access_token = CfDJ8Fl243zyrVdFr9oC_M2D9Gg4t9okXa2Bd9gKGNAuXREIHSDbkKEZlCdUUaXZzuqIJplpM0dvPGAnG1WatVUrlEhtp0iqPX2AJ9Fe3_D9EkA4STevW1ybJX-qXV3on3L7gTWZO8oS6FQ2ZwNvzJF1yQ9faZafEnH_ibPgjtVbwLtmRm-pJ5zL5Mpny0W_Ry2l-9Al5SQgbabnoJ7lQ_GnVJItKoShZt2ynfCzwniCTJhcdBeSf3VfD_VLs_hhBxTwwASUmXSV7NwdLFTyJReq5Q3Z_kXpgea1bqZimBuTfQCo_71OxdxbsA0FOIiWOnR109I_ytm5LLDZomkg3TMP-prJXodbP-wq25vot4dEwH_iPx0qvxzUrJ8s6RDEdbw_hvlGrE_LPKu8iPUVnwcCWo36HCrluAIqscwO1OVW8xnqdLJDpd65OCrbuDwvPGNlVwqEP18NVSwJ8PUL9tvDNOhQ3tT-zFa3pK0aTes20PO1yIZaym3JNUSHGWZvobP0u3k42rAHcsNTZ9ec2OfyuRIZZYk2dZgNo4f5KNVWqhWAvK9gVIDvbnPIVNesWDSahIHXyLqifkZ0RxmNlVVAyhYcJ7M6je65kCfTXu9SCY8l1SoDNrN8lfx4iGLfHK1lxutWI6BRbF904EpVRq4aYHGTwgFcRYiRJW8o1Dd_cX7MEx0a1H4nwEyqRtqadexZXw
POST {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/logout
Accept: application/json
Authorization: Bearer {{access_token}}

### WITHOUT BEARER TOKENS #################################################

### Login - With query parameters
# Returns: No bearer tokens, only 200 OK
# bool? useCookies: When true, the endpoint does a standard cookie-based login, and doesn't return access tokens
@useCookies = true
# bool? useSessionCookies: When false, the cookies are set as "session" cookies, so they are removed when you close your browser.
@useSessionCookies = true
POST {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/login?useCookies={{useCookies}}&useSessionCookies={{useSessionCookies}}
Accept: application/json
Content-Type: application/json

{
  "email": "user@test.com",
  "password": "P@ssw0rd!"
}

###

### LogOut - At AccountApiController
# 
POST {{CleanArchitectureTemplate.Server_HostAddress}}/api/AccountApi/logout
Accept: application/json
Content-Type: application/json

### OTHER #################################################################

### Refresh token
POST {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/refresh
Accept: application/json
Content-Type: application/json

{
  "refreshToken": "<REFRESH_TOKEN>"
}

###

### Confirm email
GET {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/confirmEmail?userId=<USER_ID>&code=<CONFIRMATION_CODE>
Accept: application/json

###

### Resend confirmation email
POST {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/resendConfirmationEmail
Accept: application/json
Content-Type: application/json

{
  "email": "user@test.com"
}

###

### Forgot password
POST {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/forgotPassword
Accept: application/json
Content-Type: application/json

{
  "email": "user@test.com"
}

###

### Reset password
POST {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/resetPassword
Accept: application/json
Content-Type: application/json

{
  "email": "user@test.com",
  "resetCode": "<RESET_CODE>",
  "newPassword": "NewP@ssw0rd!"
}

###

### Enable / disable 2FA
POST {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/manage/2fa
Accept: application/json
Authorization: Bearer <ACCESS_TOKEN>

{
  "enable": true
}

###

### Get user info
GET {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/manage/info
Accept: application/json
Authorization: Bearer <ACCESS_TOKEN>

###

### Update user info
POST {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/manage/info
Accept: application/json
Authorization: Bearer <ACCESS_TOKEN>
Content-Type: application/json

{
  "email": "newemail@test.com",
  "phoneNumber": "+5491112345678"
}

###

### Get profile
GET {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/profile
Accept: application/json
Authorization: Bearer <ACCESS_TOKEN>

###

### Get profile
GET {{CleanArchitectureTemplate.Server_HostAddress}}/api/identity/profile
Accept: application/json
