services:

  simplemonolithtemplate.monolith:
    image: ${DOCKER_REGISTRY-}simplemonolithtemplatemonolith
    build:
      context: .
      dockerfile: solution/SimpleMonolithTemplate.Monolith/Dockerfile
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=SimpleMonolithTemplateDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrongPassword123!"
