using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BasicNtierTemplate.Data.Model
{
    public partial class Course
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // Primary key values are provided by the user rather than generated by the database.
        [Display(Name = "Number")]
        public int CourseId { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 3)]
        public string Title { get; set; } = string.Empty;

        [Range(0, 5)]
        public int Credits { get; set; }

        public int DepartmentId { get; set; }

        public Department Department { get; set; } = default!;

        // A course can have any number of students enrolled in it, so the Enrollments navigation property is a collection.
        public ICollection<Enrollment> Enrollments { get; set; } = [];

        // A course may be taught by multiple instructors, so the CourseAssignments navigation property is a collection.
        public ICollection<CourseAssignment> CourseAssignments { get; set; } = [];
    }
}
