services:
  basicnlayertemplate.web:
    image: ${DOCKER_REGISTRY-}basicnlayertemplateweb
    build:
      context: .
      dockerfile: solution/BasicNLayerTemplate.Web/Dockerfile
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=BasicNLayerTemplateDb;User Id=sa;Password=Password!123;TrustServerCertificate=True;"
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "8080:8080"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: basicnlayertemplate-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password!123"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
