@ComplexNLayerTemplate.Server_HostAddress = http://localhost:5018

###

### Weather forecast endpoint
GET {{ComplexNLayerTemplate.Server_HostAddress}}/api/WeatherForecasts/data
Accept: application/json

###

### Get all students
GET {{ComplexNLayerTemplate.Server_HostAddress}}/api/ContosoUniversity/students
Accept: application/json

###

### Get student by Id
@studentId = 1
GET {{ComplexNLayerTemplate.Server_HostAddress}}/api/ContosoUniversity/students/{{studentId}}
Accept: application/json

###

### Create student
POST {{ComplexNLayerTemplate.Server_HostAddress}}/api/ContosoUniversity/students
Content-Type: application/json

{
  "firstMidName": "John",
  "lastName": "Doe",
  "governmentId": "123456789",
  "enrollmentDate": "2026-01-01",
  "Enrollments": []
}


###

### Update student
@studentId = 1
PUT {{ComplexNLayerTemplate.Server_HostAddress}}/api/ContosoUniversity/students/{{studentId}}
Content-Type: application/json

{
  "firstMidName": "John New",
  "lastName": "Doe Old",
  "governmentId": "123456789",
  "enrollmentDate": "2026-01-01"
}

###

### Delete student
@studentId = 99
DELETE {{ComplexNLayerTemplate.Server_HostAddress}}/api/ContosoUniversity/students/{{studentId}}

###
